on: ['push', 'pull_request']
name: 'go test'

jobs:
  test:
    strategy:
      matrix:
        go-version: ['1.13.x', '1.14.x', '1.15.x', '1.16.x']
        os:         ['ubuntu-latest', 'macos-latest', 'windows-latest']
    runs-on: '${{ matrix.os }}'
    steps:

    - name: 'Install Go'
      uses: 'actions/setup-go@v2'
      with:
        go-version: '${{ matrix.go-version }}'

    - name: 'Checkout code'
      uses: 'actions/checkout@v2'

    - name: 'Install'
      run: |
        go install ./...
        curl -Ls 'https://github.com/BurntSushi/toml-test/releases/download/1.0.0-beta1/toml-test-v1.0.0-beta1-linux-amd64.gz' |
            gzip -d - > toml-test
        chmod a+x ./toml-test

    - name: 'Test'
      run: 'make TOML_TEST=./toml-test'
